module.exports = {
  testEnvironment: "jsdom",
  // roots: ["<rootDir>", "<rootDir>/src/__mocks__"],
  moduleNameMapper: {
    "\\.(css|less|scss)$": "identity-obj-proxy",
    "^@src/(.*)$": "<rootDir>/src/$1",
    "^@assets/(.*)$": "<rootDir>/src/assets/$1",
    "^@components/(.*)$": "<rootDir>/src/components/$1",
    "^@constant/(.*)$": "<rootDir>/src/constant/$1",
    "^@context/(.*)$": "<rootDir>/src/context/$1",
    "^@layout/(.*)$": "<rootDir>/src/layout/$1",
    "^@routes/(.*)$": "<rootDir>/src/routes/$1",
    "^@style/(.*)$": "<rootDir>/src/style/$1",
    "^@pages/(.*)$": "<rootDir>/src/pages/$1",
    "^@themes/(.*)$": "<rootDir>/src/themes/$1",
    "^@types/(.*)$": "<rootDir>/src/ts/types/$1",
    "^@test/(.*)$": "<rootDir>/src/__test__/$1",
    "^@utils/(.*)$": "<rootDir>/src/utils/$1",
    "^@ts/(.*)$": "<rootDir>/src/ts/$1",
    "^@hooks/(.*)$": "<rootDir>/src/hooks/$1",
    "^@hoc/(.*)$": "<rootDir>/src/hoc/$1",
  },
  transform: {
    "^.+\\.[t|j]sx?$": "babel-jest",
    "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$":
      "<rootDir>/fileTransformer.cjs",
  },
  collectCoverage: false,
  collectCoverageFrom: [
    "<rootDir>/src/**/*.{ts,tsx}",
    "!<rootDir>/src/themes/*.ts",
    "!<rootDir>/src/hoc/*.tsx",
    "!<rootDir>/src/ts/*.ts",
    "!<rootDir>/src/test-utils/*.{ts,tsx}",
    "!<rootDir>/src/constant/*.{ts,tsx}",
    "!<rootDir>/src/**/*.d.ts",
    "!<rootDir>/src/constants/*.test.*",
  ],
};
